//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Admin
    {
        [Required(ErrorMessage = "This Field is Required")]
        [Display(Name = "Id")]
        public int IdUs { get; set; }

        [Required(ErrorMessage = "This Field is Required")]
        [Display(Name = "Username")]
        public string UserNameUs { get; set; }

        [Required(ErrorMessage = "This Field is Required")]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        [MinLength(8, ErrorMessage = "Minimum 8 characters required")]

        public string PasswordUs { get; set; }

        [Required(ErrorMessage = "This Field is Required")]
        [Display(Name = "Confirm Password")]
        [DataType(DataType.Password)]
        [Compare("PasswordUs", ErrorMessage = "Confirm password does n't match, type again!")]
        [NotMapped]
        public string RePasswordUs { get; set; }

        [Required(ErrorMessage = "This Field is Required")]
        [Display(Name = "New Password")]
        [DataType(DataType.Password)]
        [NotMapped]
        public string NewPasswordUs { get; set; }

        [Required(ErrorMessage = "This Field is Required")]
        [Display(Name = "Confirm New Password")]
        [DataType(DataType.Password)]
        [Compare("NewPasswordUs", ErrorMessage = "New Confirm password does n't match, type again!")]
        [NotMapped]
        public string ReNewPasswordUs { get; set; }


    }
}
