//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Employee_Login
    {
        [Required(ErrorMessage = "This Field is Required")]
        [Display(Name = "Id")]
        public string id { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        [Display(Name = "Role")]
        public string role { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        [MinLength(6, ErrorMessage = "Minimum 6 characters required")]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^\da-zA-Z]).{8,15}$", ErrorMessage = "Password must be between 8 and 15 characters and should have atleast one uppercase,lowercase,digit and special character")]
        public string password { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        [Display(Name = "RePassword")]
        [DataType(DataType.Password)]
        [NotMapped]
        [Compare("password", ErrorMessage = "Confirm password does n't match, type again!")]
        public string repassword { get; set; }
    }
}
