//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Employee
    {
        [Required(ErrorMessage = "This Field is Required")]
        public int id { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public string Name { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public string Date_of_birth { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public string Father_Name { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public string Mother_Name { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public string Address { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public Nullable<int> Salary { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public string Fresher { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public string Role { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public string Notes { get; set; }
    }
}
