//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Leave_request
    {
        public int id { get; set; }
        [Required(ErrorMessage = "Employee Id is required")]
        [Display(Name = "Employee Id")]
        public int emp_id { get; set; }
        [Required(ErrorMessage = "Employee Name is required")]
        [Display(Name = "Employee Name")]
        public string emp_name { get; set; }
        [Required(ErrorMessage = "Start Date is required")]
        [Display(Name = "Start Date")]
        [DataType(DataType.Date)]
        public string start_date { get; set; }
        [Required(ErrorMessage = "End Date is required")]
        [Display(Name = "End Date")]
        [DataType(DataType.Date)]
        public string end_date { get; set; }
        [Required(ErrorMessage = "Leave Type is required")]
        [Display(Name = "Leave Type")]
        public string leave_type { get; set; }
        [Required(ErrorMessage = "Reason is required")]
        [Display(Name = "Reason")]
        public string reason { get; set; }
        [Required(ErrorMessage = "Reference Number is required")]
        [Display(Name = "Reference No")]
        public string ref_no { get; set; }
        public string status { get; set; }
        [Required(ErrorMessage = "Support Document is required")]
        [Display(Name = "Support Document")]
        public string file_name { get; set; }
        public string Content_type { get; set; }
        public byte[] file_data { get; set; }
        public int Active { get; set; }
        public string Comments { get; set; }
    }
}
